---
- name: Create Ansible Platform Team
  ansible.platform.team:
    name:                     "{{ __platform_team_item.name | mandatory }}"
    new_name:                 "{{ __platform_team_item.new_name | default(omit, true) }}"
    description:              "{{ __platform_team_item.description | default(( '' if platform_configuration_teams_enforce_defaults else omit), true) }}"
    organization:             "{{ __platform_team_item.organization.name | default(__platform_team_item.organization) | mandatory }}"
    state:                    "{{ __platform_team_item.state | default(platform_state | default('present')) }}"

    # Role Standard Options
    gateway_config_file:   "{{ gateway_config_file | default(omit, true) }}"
    gateway_hostname:          "{{ gateway_hostname | default(omit, true) }}"
    gateway_password:      "{{ gateway_password | default(omit, true) }}"
    gateway_username:      "{{ gateway_username | default(omit, true) }}"
    gateway_token:    "{{ gateway_token | default(omit, true) }}"
    gateway_request_timeout:          "{{ gateway_request_timeout | default(omit, true) }}"
    gateway_validate_certs:           "{{ gateway_validate_certs | default(omit) }}"
  loop: "{{ teams if teams is defined else platform_teams }}"
  loop_control:
    loop_var: __platform_team_item
  no_log: "{{ platform_configuration_teams_secure_logging }}"
  async: 1000
  poll: 0
  register: __platform_team_job_async
  changed_when: not __platform_team_job_async.changed
  vars:
    ansible_async_dir: '{{ platform_configuration_async_dir }}'

- name: "Configure Teams | Wait for finish the Teams creation"
  ansible.builtin.async_status:
    jid: "{{ __platform_team_job_async_results_item.ansible_job_id }}"
  register: __platform_team_job_async_result
  until: __platform_team_job_async_result.finished
  retries: "{{ platform_configuration_teams_async_retries }}"
  delay: "{{ platform_configuration_teams_async_delay }}"
  loop: "{{ __platform_team_job_async.results }}"
  loop_control:
    loop_var: __platform_team_job_async_results_item
  when: __platform_team_job_async_results_item.ansible_job_id is defined
  no_log: "{{ platform_configuration_teams_secure_logging }}"
  vars:
    ansible_async_dir: '{{ platform_configuration_async_dir }}'
...
