---
# These are the default variables specific to the teams role
platform_teams: []
platform_configuration_teams_secure_logging: "{{ platform_configuration_secure_logging | default('false') }}"
platform_configuration_teams_async_retries: "{{ platform_configuration_async_retries | default(30) }}"
platform_configuration_teams_async_delay: "{{ platform_configuration_async_delay | default(1) }}"
platform_configuration_async_dir: null
platform_configuration_teams_enforce_defaults: "{{ platform_configuration_enforce_defaults | default(false) }}"
...
